version: "3.8"

services:
  app:
    build: .
    container_name: book-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - /home/deploy/book-management-api/.env.properties:/app/.env.properties:ro
    environment:
      - SPRING_PROFILES_ACTIVE=prod